package com.inventory.product_service.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * A product in the catalogue. This is a <em>persistence</em> class: its job is to mirror the
 * {@code products} table, nothing more.
 *
 * <p><strong>This type never leaves the service.</strong> Controllers accept and return DTOs
 * instead (see {@code dto/}). Two reasons, and both bite in practice:
 *
 * <ul>
 *   <li><em>Coupling.</em> If this class is your API, renaming a column becomes a breaking
 *       change for every caller in the system.</li>
 *   <li><em>Accidental data leaks.</em> Serializing an entity walks its relations. Add one
 *       lazy {@code @OneToMany} later and Jackson will either drag half the database into
 *       the response or blow up with a {@code LazyInitializationException} - a failure that
 *       only shows up once the transaction has already closed.</li>
 * </ul>
 *
 * <p>Note what is deliberately absent: Lombok's {@code @Data}. It generates
 * {@code equals}/{@code hashCode} over every field, including the generated id (which is
 * null until the row is inserted, so an entity's hash changes mid-transaction and breaks any
 * {@code HashSet} holding it) and a {@code toString} that touches lazy relations and fires
 * surprise queries. {@code @Getter}/{@code @Setter} are the safe subset for JPA entities.
 */
@Entity
@Table(name = "products")
@Getter
@Setter
@NoArgsConstructor          // JPA requires a no-arg constructor to instantiate rows reflectively
@AllArgsConstructor
@Builder
public class Product {

    /**
     * Internal surrogate key. Generated by the database ({@code BIGSERIAL}).
     *
     * <p>{@code IDENTITY} means Hibernate lets Postgres assign the value on INSERT. The
     * trade-off is that it cannot batch inserts, because it must round-trip to learn each
     * id. {@code SEQUENCE} allows batching by pre-allocating ids, and is the better default
     * for write-heavy services - a good thing to remember when someone asks why their bulk
     * insert is slow.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The public business key. Other services (inventory-service, order-service) identify a
     * product by SKU, never by {@link #id}.
     *
     * <p>This split matters architecturally: {@code id} is an implementation detail of
     * <em>this</em> database and we stay free to change how it is generated. {@code sku} is a
     * contract with the rest of the system, so it is immutable once published.
     */
    @Column(nullable = false, unique = true, length = 64, updatable = false)
    private String sku;

    @Column(nullable = false)
    private String name;

    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * Money is {@link BigDecimal}, never {@code double} or {@code float}.
     *
     * <p>Binary floating point cannot represent 0.1 exactly, so {@code 0.1 + 0.2} is
     * {@code 0.30000000000000004}. Over enough rows that becomes a real accounting bug.
     * {@code NUMERIC(12,2)} in Postgres maps to exact-precision decimal arithmetic.
     */
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal price;

    /** Set once on insert. {@code updatable = false} makes later changes impossible. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * JPA lifecycle callbacks. Hibernate invokes these around the INSERT and UPDATE, so the
     * timestamps are maintained in one place instead of being set by hand in every service
     * method - the kind of thing that is always correct until the one caller that forgets.
     *
     * <p>{@link Instant} (UTC, unambiguous) rather than {@code LocalDateTime}, which carries
     * no zone and turns into a guessing game the moment two services run in two regions.
     * Spring Data's {@code @CreatedDate}/{@code @LastModifiedDate} auditing does the same
     * job declaratively once you have several entities.
     */
    @PrePersist
    void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    @PreUpdate
    void onUpdate() {
        this.updatedAt = Instant.now();
    }
}
